name: boredom
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_svg: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/bored-girl-launcher.png
    - lib/assets/bored-girl.png
    - lib/assets/bored-boy.png
    - lib/assets/dartboard.png
    - lib/assets/dart.png

flutter_icons:
  android: true
  ios: true
  image_path: lib/assets/bored-girl.png
  remove_alpha_ios: true

flutter_native_splash:
  color: "#E8E7E7"
  image: lib/assets/bored-girl-launcher.png
  android_12:
    image: lib/assets/bored-girl-launcher.png
    icon_background_color: "#E8E7E7"
  android: true
  ios: true
